# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 737ce24a9c7912963618c18cd2c1f326874f725e6e00b15149000aadca5661cce77d89435c70b568193dca26ccca0868a30a70dcbbd92f24a2ff4751b5311d26

test:
  secret_key_base: de06a824621f590d803fb11ec6f7535597a44f6007d7d1d58c776c98c91f7b33546784abf19ebe1cd8471b871fb36b7422c2905aaeb6e697ff462c0b390b33c5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
